### PR TITLE
Added links to elmah.io

### PR DESCRIPTION
**Pull request by ThomasArdal**
Here are the changes in regards to the sponsored post. I also updated the link to the ELMAH open source project, since that moved from google code to GitHub recently.

### CODE REVIEW

**Comment by dustinmoris** [comment]
Looks good to me. I will go ahead with the merge when I'm back home this evening ! Thank you!

**Comment by ThomasArdal** [comment]
Sounds great. I just updated the urls with some google analytics campaign data.

**Comment by dustinmoris** [comment]
Build just finished and its live https://dusted.codes/demystifying-aspnet-mvc-5-error-pages-and-error-logging

**Comment by ThomasArdal** [comment]
Awesome. Thanks.

**Pull request merged**
